### PR TITLE
add ci and dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by PiyushXCoder** [comment]
Hi,
I understand the purpose of [dependabot.yml](https://github.com/PiyushXCoder/post_maker/pull/1/files#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28), but Idk why we need [rust.yml](https://github.com/PiyushXCoder/post_maker/pull/1/files#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792d).

The [rust.yml](https://github.com/PiyushXCoder/post_maker/pull/1/files#diff-73e17259d77e5fbef83b2bdbbe4dc40a912f807472287f7f45b77e0cbf78792d) doesn't do anything with the build.

Also I can see that you added windows-latest, macos-latest, ubuntu-latest while `build app` explicitly check for `${RUNNER_OS} == "Linux"`

**Comment by theavege** [comment]
Hi. "Rust.yml" adds a build check on Linux (can be enabled for Windows and MacOS). Should I remove it?

**Comment by PiyushXCoder** [comment]
Ok cool, I will merge it, with some changes.

* Comment out windows and macos for now
  ```yml
  - windows-latest
  - macos-latest
  ```
* The action should trigger only when there are changes to `master` branch
* Release the build

**Comment by PiyushXCoder** [comment]
I have assigned it to you.

Make  the changes so I can merge.

Thank you for enhancements!

**Comment by theavege** [comment]
I have done. Your program is good. Could you report [there](https://github.com/fltk-rs/fltk-rs/issues/418) about PostMaker?

**Comment by PiyushXCoder** [comment]
I have merged, I will add the project there.

Thank you for your work

**Comment by theavege** [comment]
[FYI](https://github.com/CM-IV/crypto_rs/pull/2#issuecomment-2403377887)

**Pull request merged**
